### ISSUE TITLE
Error Undefined index: slack_webhook on line 23 of Airtable.php 

### ISSUE THREAD

**Issue by jjokham** [sleiman/airtable-php#28]
I get the above error after initializing the class.

**Comment by jjokham** [comment]
i get the above error after initializing the class.

**Comment by sleiman** [comment]
@jjokham you're using the latest version of the wrapper, it shouldn't give you an error if you're not using the slack_webhook, I will look into this now. Thanks for bringing it up. 

Look at this example, it shows the update.
https://github.com/sleiman/airtable-php/blob/master/examples/slack-notification.php

If you install the plugin with composer, you won't have this problem.

Let me know if this helps

**Comment by jjokham** [comment]
unfortunately, i am not using composer and it still shows the error. Also, once I commented it out. I tried to get values from a table and it just shows null. Although I do have values there. I tried with my own function and I can retrieve the values. Can you look into it. 

Thanks for writing the wrapper.

**Comment by sleiman** [comment]
@jjokham can you try again? I just pushed a fix. Sorry about that! Let me know if it worked.
Thank you!

**Comment by jjokham** [comment]
Yes. It works. But, am still getting null values from a table which has values.

**Comment by sleiman** [comment]
Can you share that part of your code with me?

**Comment by jjokham** [comment]
declare(strict_types =1);

include("Airtable.php");
include("Request.php");
include("Response.php");

use \TANIOS\Airtable\Airtable;
$airtable = new Airtable(array(
    'api_key' => 'xxxxx',
    'base'    => 'xxxx'
));

$request = $airtable->getContent( 'properties' );

do {
    $response = $request->getResponse();
    var_dump( $response[ 'records' ] );
}
while( $request = $response->next() );

print_r($request);



above gives output null

**Comment by sleiman** [comment]
Is the table name "properties" all lowercase on the Airtable interface?

**Comment by jjokham** [comment]
![image](https://user-images.githubusercontent.com/12502586/51795599-1f487300-219b-11e9-9ee8-c2cd77f0a25c.png)

yup

**Comment by sleiman** [comment]
It works fine here with exactly your code. Can you double check your API Key and Base ID? That's the only time I get NULL on a request like that.

**Comment by jjokham** [comment]
yes. i checked again. api key and base id are correct. 
![image](https://user-images.githubusercontent.com/12502586/51795937-aa2b6c80-219f-11e9-9901-cc3967d6de67.png)

![image](https://user-images.githubusercontent.com/12502586/51795957-07bfb900-21a0-11e9-835f-45821d7aa7f5.png)

**Comment by jjokham** [comment]
same base and apikey

**Comment by sleiman** [comment]
Do you have CURL enabled in your environment?

**Comment by jjokham** [comment]
yes. 

![image](https://user-images.githubusercontent.com/12502586/51796006-cda2e700-21a0-11e9-9469-d06ddaedcfb7.png)

**Comment by sleiman** [comment]
Can you try `var_dump($airtable);`  and tell me what it says?

**Comment by jjokham** [comment]
![1](https://user-images.githubusercontent.com/12502586/51796202-95040d00-21a2-11e9-8976-4dd2b98e89c8.png)

**Comment by sleiman** [comment]
Thank you!

Please download the files one more time, I removed all the slack integration from the master. Let me know this solves the problem

**Comment by jjokham** [comment]
![1](https://user-images.githubusercontent.com/12502586/51796240-88cc7f80-21a3-11e9-90eb-466a5177b6bf.png)

Still shows NULL

**Comment by sleiman** [comment]
Can you email me at sleiman@tanios.ca ? If you don't mind, I will add you to our Slack or if you prefer another chat, it will be easier to figure out what's going on.

**Comment by jjokham** [comment]
sure
